# Generated by Django 5.0.6 on 2024-05-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('ward', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=999)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
