# Generated by Django 4.1 on 2024-05-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalequipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employes',
            name='type_of_action',
            field=models.CharField(default='none', max_length=999),
            preserve_default=False,
        ),
    ]
