# Generated by Django 4.1 on 2024-05-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalequipment', '0002_employes_type_of_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployesClothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_of_employe', models.IntegerField()),
                ('description', models.CharField(max_length=999)),
                ('type_of_action', models.CharField(max_length=999)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='employes',
            name='created',
        ),
        migrations.RemoveField(
            model_name='employes',
            name='description',
        ),
        migrations.RemoveField(
            model_name='employes',
            name='type_of_action',
        ),
    ]
