# Generated by Django 5.0.6 on 2024-05-31 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalequipment', '0003_employesclothes_remove_employes_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employesclothes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
